services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "127.0.0.1:6379:6379"
  keycloak:
    container_name: keycloak
    image: keycloak
    ports:
      - "127.0.0.1:8085:8080"
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_PASSWORD: "admin"
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "127.0.0.1:15672:15672"
      - "127.0.0.1:5672:5672"
  discovery:
    build:
      context: .
      dockerfile: C:/Users/Abdelrahman.Hamzeh/Demo/DiscoveryService/Dockerfile
    container_name: discovery
    ports:
      - "127.0.0.1:8761:8761"
  gateway:
    build:
      context: .
      dockerfile: C:/Users/Abdelrahman.Hamzeh/Demo/Gateway/Dockerfile
    container_name: gateway
    ports:
      - "127.0.0.1:9000:9000"
    depends_on:
      - discovery