server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
spring:
  application:
    name: GATEWAY
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: BookRoute
          uri: lb://BOOKS
          predicates:
            - Path=/Book/**
        - id: AuctionRoute
          uri: lb://AUCTION
          predicates:
            - Path=/Auction/**
        - id: WishListRoute
          uri: lb://WISHLIST
          predicates:
            - Path=/Wishlist/**
        - id: UserRoute
          uri: lb://USER
          predicates:
            - Path=/auth/**
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: bookstore-client
            client-secret: fyIWlMtbdAUAHe75O0dJNkHGLeIouL8H
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8085/realms/bookstore-realm
  data:
    redis:
      host: localhost
      port: 6379