server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
spring:
  application:
    name: GATEWAY
  cloud:
    gateway:
      default-filters:
        - TokenRelay
        - name: RequestRateLimiter
          args:
            redis-rate-limiter:
              replenishRate: 10
              burstCapacity: 20
              requestedTokens: 1
        - name: CircuitBreaker
          args:
            name: fallBackService
            fallbackUri: forward:/Handle-Failure
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: BookRoute
          uri: lb://BOOKS
          predicates:
            - Path=/Book/**
        - id: AuctionRoute
          uri: lb://AUCTION
          predicates:
            - Path=/Auction/**
        - id: WishListRoute
          uri: lb://WISHLIST
          predicates:
            - Path=/Wishlist/**
        - id: UserRoute
          uri: lb://USER
          predicates:
            - Path=/auth/**
        - id: AuthorRoute
          uri: lb://AUTHOR
          predicates:
            - Path=/Author/**
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: bookstore-client
            client-secret: GN5fLteQS3M7VqWDelbJiBn9elJZCFYo
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:8085/realms/bookstore-realm
  data:
    redis:
      host: localhost
      port: 6379